# Generated by Django 3.0.6 on 2021-07-25 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('productnumber', models.CharField(db_column='ProductNumber', max_length=52)),
                ('productname', models.CharField(db_column='ProductName', max_length=255)),
                ('imglink', models.CharField(db_column='ImgLink', max_length=255)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('storename', models.CharField(db_column='StoreName', max_length=255)),
            ],
            options={
                'db_table': 'Stores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linkforeachproductinstore',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.Products')),
                ('link', models.CharField(db_column='Link', max_length=400, unique=True)),
            ],
            options={
                'db_table': 'LinkForEachProductInStore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricesforeachstore',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.Products')),
                ('isavailable', models.BooleanField(db_column='IsAvailable')),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
            ],
            options={
                'db_table': 'PricesForEachStore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersSubscriptions',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isAvaible', models.BooleanField(db_column='IsAvaible')),
                ('Price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('productId', models.ForeignKey(db_column='ProductId', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Products')),
                ('userid', models.ForeignKey(db_column='UserId', default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsersSubscriptions',
                'unique_together': {('userid', 'productId')},
            },
        ),
    ]
